[18-Aug-2019 20:42:22 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined property: App\Models\User::$password'
Stack trace: #0 C:\xampp\htdocs\mvc\App\Models\User.php(34): Core\Error::errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\mvc\App\Controllers\Signup.php(51): App\Models\User->save()
#2 [internal function]: App\Controllers\Signup->createAction()
#3 C:\xampp\htdocs\mvc\Core\Controller.php(47): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\mvc\Core\Router.php(119): Core\Controller->__call('create', Array)
#5 C:\xampp\htdocs\mvc\public\index.php(44): Core\Router->dispatch('signup/create')
#6 {main}
Thrown in 'C:\xampp\htdocs\mvc\App\Models\User.php' on line 34
[18-Aug-2019 20:42:35 Europe/Berlin] Uncaught exception: 'ErrorException' with message 'Undefined property: App\Models\User::$password'
Stack trace: #0 C:\xampp\htdocs\mvc\App\Models\User.php(34): Core\Error::errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 34, Array)
#1 C:\xampp\htdocs\mvc\App\Controllers\Signup.php(51): App\Models\User->save()
#2 [internal function]: App\Controllers\Signup->createAction()
#3 C:\xampp\htdocs\mvc\Core\Controller.php(47): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\mvc\Core\Router.php(119): Core\Controller->__call('create', Array)
#5 C:\xampp\htdocs\mvc\public\index.php(44): Core\Router->dispatch('signup/create')
#6 {main}
Thrown in 'C:\xampp\htdocs\mvc\App\Models\User.php' on line 34
